/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aforcado.view;

import aforcado.model.HangMan;
import aforcado.ui.ArrayWordGenerator;
import aforcado.ui.GUIKeyboardWordGenerator;
import aforcado.ui.GenerateWordException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 * Ventana principal da aplicación
 * @author Abel Iglesias Moure
 */
public class MainWindow extends javax.swing.JFrame {

    private HangMan hangMan;
    private JLabel[] hangManLabels;

    public HangMan getHangMan() {
        return hangMan;
    }

    public void setHangMan(HangMan hangMan) {
        this.hangMan = hangMan;
    }

    public JLabel[] getHangManLabels() {
        return hangManLabels;
    }

    public void setHangManLabels(JLabel[] hangManLabels) {
        this.hangManLabels = hangManLabels;
    }

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        hangManLabels = new JLabel[]{img0, img1, img2, img3, img4, img5, img6};
        jPanelRigth.add(img6);
    }

    private void startNewGame() {
        String[] options = {"Un xogador, xerando a palabra ao azar", "Dous xogadores, introduce unha palabra por teclado"};
        String optionUser = (String) JOptionPane.showInputDialog(this, "Selecciona un modo de xogo", "Modo de xogo", JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

        if (optionUser != null) {

            boolean newGame = false;

            //Se escolle a opción de un xogador
            if (optionUser.equals(options[0])) {
                hangMan = new HangMan(new ArrayWordGenerator().generateWord());
                newGame = true;
            //Se elixe introducir a palabra por teclado
            } else {
                try {
                    hangMan = new HangMan(new GUIKeyboardWordGenerator().generateWord());
                    newGame = true;
                } catch (GenerateWordException ex) {
                    if (ex.isVisible()) {
                        System.err.println(ex.getMessage());
                    }
                }
            }
            
            if (newGame) {
                jText.setEnabled(true);
                jButtonProve.setEnabled(true);
                showGameStatus();
            }
        }

    }

    private void showGameStatus() {
        jPanelRigth.remove(jPanelRigth.getComponent(0));
        jPanelRigth.add(hangManLabels[hangMan.getFails().size()]);

        jLabelHiddenWord.setText(hangMan.showHiddenWord());
        jLabelLettersFails.setText(hangMan.getStringFails());

        if (hangMan.isGameOver()) {
            if (hangMan.maxFailsExceeded()) {
                JOptionPane.showMessageDialog(this, "Fin do xogo. Quedaches aforcado!! A palabra oculta era " + hangMan.showFullWord(), "Game Over", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Felicidades!! Gañaches a partida", "Partida Gañada", JOptionPane.INFORMATION_MESSAGE);
            }
            jText.setEnabled(false);
            jButtonProve.setEnabled(false);
        }
    }

    private void tryChar() {
        if (!jText.getText().isEmpty() && jText.getText().matches("^[\\p{L}\\p{IsLatin}]+$")) {
            hangMan.tryChar(Character.toUpperCase(jText.getText().charAt(0)));
        }else{
            JOptionPane.showMessageDialog(this, "Introduce unha letra do abecedario Español", "Letra incorrecta", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img0 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        img4 = new javax.swing.JLabel();
        img5 = new javax.swing.JLabel();
        img6 = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelBody = new javax.swing.JPanel();
        jPanelRigth = new javax.swing.JPanel();
        jPanelLeft = new javax.swing.JPanel();
        jPanelContainer = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelHiddenWord = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelLettersFails = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jText = new javax.swing.JTextField();
        jButtonProve = new javax.swing.JButton();
        jPanelFooter = new javax.swing.JPanel();
        jButtonNewGame = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();

        img0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hangman-0.png"))); // NOI18N

        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hangman-1.png"))); // NOI18N

        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hangman-2.png"))); // NOI18N

        img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hangman-3.png"))); // NOI18N

        img4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hangman-4.png"))); // NOI18N

        img5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hangman-5.png"))); // NOI18N

        img6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hangman-6.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("O aforcado");
        setMinimumSize(new java.awt.Dimension(540, 330));
        setPreferredSize(new java.awt.Dimension(540, 330));

        jLabelTitle.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabelTitle.setText("O Xogo do aforcado");
        jPanelHeader.add(jLabelTitle);

        getContentPane().add(jPanelHeader, java.awt.BorderLayout.NORTH);

        jPanelBody.setLayout(new java.awt.BorderLayout());

        jPanelRigth.setLayout(new java.awt.CardLayout());
        jPanelBody.add(jPanelRigth, java.awt.BorderLayout.EAST);

        jPanelLeft.setLayout(new java.awt.GridBagLayout());

        jPanelContainer.setLayout(new java.awt.BorderLayout());

        jPanel13.setLayout(new java.awt.GridLayout(3, 0));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Palabra a adiviñar:");
        jPanel1.add(jLabel1);

        jLabelHiddenWord.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jPanel1.add(jLabelHiddenWord);

        jPanel13.add(jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Letras falladas:");
        jPanel2.add(jLabel2);

        jLabelLettersFails.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jPanel2.add(jLabelLettersFails);

        jPanel13.add(jPanel2);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setText("Introduce unha letra:");
        jPanel3.add(jLabel4);

        jText.setColumns(5);
        jText.setEnabled(false);
        jPanel3.add(jText);

        jButtonProve.setText("Probar");
        jButtonProve.setEnabled(false);
        jButtonProve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProveActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonProve);

        jPanel13.add(jPanel3);

        jPanelContainer.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanelLeft.add(jPanelContainer, new java.awt.GridBagConstraints());

        jPanelBody.add(jPanelLeft, java.awt.BorderLayout.WEST);

        getContentPane().add(jPanelBody, java.awt.BorderLayout.CENTER);

        jPanelFooter.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jButtonNewGame.setText("Nova partida");
        jButtonNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewGameActionPerformed(evt);
            }
        });
        jPanelFooter.add(jButtonNewGame);

        jButtonExit.setText("Saír");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanelFooter.add(jButtonExit);

        getContentPane().add(jPanelFooter, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewGameActionPerformed
        startNewGame();
    }//GEN-LAST:event_jButtonNewGameActionPerformed

    private void jButtonProveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProveActionPerformed
        tryChar();
        jText.setText("");
        showGameStatus();
    }//GEN-LAST:event_jButtonProveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img0;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel img4;
    private javax.swing.JLabel img5;
    private javax.swing.JLabel img6;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonNewGame;
    private javax.swing.JButton jButtonProve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelHiddenWord;
    private javax.swing.JLabel jLabelLettersFails;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelContainer;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelRigth;
    private javax.swing.JTextField jText;
    // End of variables declaration//GEN-END:variables
}
